from __future__ import annotations

import random


NAME_SETS = [
    ("沈岚", "周启明", "程诺", "顾言"),
    ("苏晴", "陈默", "陆川", "许知远"),
    ("林夏", "贺文博", "唐玥", "江屿"),
    ("叶澄", "孟修远", "乔安", "韩知行"),
]


def build_fallback_case(seed: str) -> dict:
    rng = random.Random(seed)
    alice_name, bob_name, charlie_name, david_name = rng.choice(NAME_SETS)
    case_number = rng.randint(11, 98)

    return {
        "schema_version": "1.0",
        "title": f"静默温室 · 档案 {case_number}",
        "setting": "澄湾生命科学中心",
        "victim": {"name": "林越教授", "role": "植物毒理学项目负责人"},
        "location": "B3 恒温实验室",
        "death_window": "19:55–20:10",
        "summary": (
            "林越教授被发现倒在反锁的恒温实验室内。现场没有明显打斗痕迹，"
            "一支破裂的蓝色试剂瓶却出现在本不该使用该试剂的实验台上。"
        ),
        "public_timeline": [
            {"time": "19:35", "event": "林越教授独自进入 B3 恒温实验室"},
            {"time": "19:55–20:10", "event": "法医推定的死亡时间窗口"},
            {"time": "20:22", "event": f"{david_name} 发现异常并通知保安"},
        ],
        "culprit_id": "bob",
        "motive": "掩盖伪造实验数据并阻止林越教授在次日评审会上公开撤销论文署名",
        "method": "将高浓度乌头碱混入教授固定饮用的无糖咖啡，并用临时门禁卡制造密室假象",
        "truth_summary": (
            f"{bob_name} 得知林越教授准备公开其数据造假后，提前取走乌头碱。"
            "他在 20:01 使用一张临时门禁卡进入 B3，把毒物加入咖啡，"
            "随后从维护通道离开，并谎称自己整晚都在图书馆。"
        ),
        "truth_timeline": [
            {"time": "18:40", "event": f"{bob_name} 从公共试剂柜取走乌头碱，登记用途为昆虫实验"},
            {"time": "19:42", "event": f"{charlie_name} 听见林越教授与 {bob_name} 因论文数据激烈争执"},
            {"time": "20:01", "event": f"{bob_name} 使用未实名的临时门禁卡进入 B3"},
            {"time": "20:04", "event": f"{bob_name} 将乌头碱加入咖啡，并从维护通道离开"},
            {"time": "20:07", "event": "林越教授中毒倒地，智能手表记录到心律骤变"},
            {"time": "20:22", "event": f"{david_name} 发现实验室内有人倒地并报警"},
        ],
        "suspects": [
            {
                "id": "alice",
                "name": alice_name,
                "role": "博士后研究员",
                "initials": alice_name[-2:],
                "public_bio": "负责温室样本与门禁日志复核，做事精确，近期与教授意见不合。",
                "personality": "冷静、谨慎、说话简短",
                "secret": "她私下申请了另一所研究所的职位，担心教授阻挠离职。",
                "claims": [
                    {
                        "id": "alice_alibi",
                        "topic": "alibi",
                        "truthfulness": "TRUTH",
                        "content": "19:50 到 20:15 我一直在一楼培养室，自动移液器的操作记录能证明。",
                        "contradicts": "",
                    },
                    {
                        "id": "alice_relationship",
                        "topic": "relationship",
                        "truthfulness": "LIE",
                        "content": "我和林教授没有任何私人矛盾，我们一直合作得很顺利。",
                        "contradicts": "她因准备离职与教授发生过争执。",
                    },
                    {
                        "id": "alice_last_seen",
                        "topic": "last_seen",
                        "truthfulness": "TRUTH",
                        "content": "我最后见到林教授是 19:30，他拿着咖啡进了 B3。",
                        "contradicts": "",
                    },
                    {
                        "id": "alice_motive",
                        "topic": "motive",
                        "truthfulness": "EVASIVE",
                        "content": "研究组最近人人都有压力，但职业分歧不等于杀人动机。",
                        "contradicts": "",
                    },
                    {
                        "id": "alice_method",
                        "topic": "method",
                        "truthfulness": "TRUTH",
                        "content": "那种蓝色瓶装的是乌头碱，正常情况下只会在二楼毒理柜里出现。",
                        "contradicts": "",
                    },
                    {
                        "id": "alice_evidence",
                        "topic": "evidence",
                        "truthfulness": "TRUTH",
                        "content": "门禁后台有一条异常记录：20:01，一张未绑定姓名的临时卡进入了 B3。",
                        "contradicts": "",
                    },
                    {
                        "id": "alice_secret",
                        "topic": "secret",
                        "truthfulness": "LIE",
                        "content": "我没有瞒着研究组做任何事。",
                        "contradicts": "她隐瞒了离职申请。",
                    },
                    {
                        "id": "alice_general",
                        "topic": "general",
                        "truthfulness": "UNKNOWN",
                        "content": "请把问题说得更具体些，时间、地点或某件证据都可以。",
                        "contradicts": "",
                    },
                ],
            },
            {
                "id": "bob",
                "name": bob_name,
                "role": "数据平台主管",
                "initials": bob_name[-2:],
                "public_bio": "负责论文数据与设备账号，原定在次日项目评审中作主要汇报。",
                "personality": "礼貌、克制、防御性强",
                "secret": "他伪造了部分药效数据，教授已决定撤下他的署名。",
                "claims": [
                    {
                        "id": "bob_alibi",
                        "topic": "alibi",
                        "truthfulness": "LIE",
                        "content": "20 点前后我一直在中心图书馆整理评审材料，从没有去过 B3。",
                        "contradicts": "20:01 的临时门禁记录和维护通道影像显示他进入过 B3。",
                    },
                    {
                        "id": "bob_relationship",
                        "topic": "relationship",
                        "truthfulness": "LIE",
                        "content": "林教授很信任我的数据，我们之间没有值得争吵的事。",
                        "contradicts": "教授已经发现数据造假并准备撤销他的署名。",
                    },
                    {
                        "id": "bob_last_seen",
                        "topic": "last_seen",
                        "truthfulness": "LIE",
                        "content": "我最后一次见他是在下午例会，大约 17 点。",
                        "contradicts": "教授的智能手表在 19:43 记录到与他的短距离设备接触。",
                    },
                    {
                        "id": "bob_motive",
                        "topic": "motive",
                        "truthfulness": "EVASIVE",
                        "content": "论文调整很正常，把学术争议说成动机太牵强了。",
                        "contradicts": "",
                    },
                    {
                        "id": "bob_method",
                        "topic": "method",
                        "truthfulness": "TRUTH",
                        "content": "毒理试剂按规定要双人领用，我没有权限单独打开教授的私人柜。",
                        "contradicts": "",
                    },
                    {
                        "id": "bob_evidence",
                        "topic": "evidence",
                        "truthfulness": "EVASIVE",
                        "content": "一张无名门禁卡说明不了持卡人是谁，更不能证明有人下毒。",
                        "contradicts": "",
                    },
                    {
                        "id": "bob_secret",
                        "topic": "secret",
                        "truthfulness": "LIE",
                        "content": "我没有改动过任何实验数据，也没有需要隐瞒的事。",
                        "contradicts": "审计记录显示他的账号批量改写了实验数据。",
                    },
                    {
                        "id": "bob_general",
                        "topic": "general",
                        "truthfulness": "UNKNOWN",
                        "content": "如果你有具体问题就直接问，我不接受没有证据的暗示。",
                        "contradicts": "",
                    },
                ],
            },
            {
                "id": "charlie",
                "name": charlie_name,
                "role": "实验室采购专员",
                "initials": charlie_name[-2:],
                "public_bio": "管理耗材采购和试剂领用，熟悉实验室全部库存。",
                "personality": "健谈、敏感、容易紧张",
                "secret": "她曾替同事补签过一次违规采购单，害怕因此被调查。",
                "claims": [
                    {
                        "id": "charlie_alibi",
                        "topic": "alibi",
                        "truthfulness": "TRUTH",
                        "content": "19:45 到 20:20 我在收货间清点冷链包裹，快递员和签收摄像头都在。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_relationship",
                        "topic": "relationship",
                        "truthfulness": "TRUTH",
                        "content": "林教授对采购流程很严格，但我们没有私人冲突。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_last_seen",
                        "topic": "last_seen",
                        "truthfulness": "TRUTH",
                        "content": f"19:42 我路过会议室时，听见林教授和 {bob_name} 在争论论文数据。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_motive",
                        "topic": "motive",
                        "truthfulness": "TRUTH",
                        "content": f"教授说第二天会公开数据审计结果，{bob_name} 当时非常激动。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_method",
                        "topic": "method",
                        "truthfulness": "TRUTH",
                        "content": "乌头碱本周只领用过一次，领用单上的用途是昆虫实验。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_evidence",
                        "topic": "evidence",
                        "truthfulness": "TRUTH",
                        "content": f"领用单由 {bob_name} 的账号提交，时间是今天 18:40。",
                        "contradicts": "",
                    },
                    {
                        "id": "charlie_secret",
                        "topic": "secret",
                        "truthfulness": "LIE",
                        "content": "每一张采购和领用单都完全合规，我从没替别人补签过。",
                        "contradicts": "她曾替同事补签违规采购单，但与本案无关。",
                    },
                    {
                        "id": "charlie_general",
                        "topic": "general",
                        "truthfulness": "UNKNOWN",
                        "content": "我能说的都在采购和领用记录里，你可以问得具体一点。",
                        "contradicts": "",
                    },
                ],
            },
            {
                "id": "david",
                "name": david_name,
                "role": "设施维护工程师",
                "initials": david_name[-2:],
                "public_bio": "负责门禁、监控与恒温系统，案发后第一个发现异常。",
                "personality": "寡言、务实、对程序问题不耐烦",
                "secret": "他发现维护通道摄像头故障后延迟报修，担心承担责任。",
                "claims": [
                    {
                        "id": "david_alibi",
                        "topic": "alibi",
                        "truthfulness": "TRUTH",
                        "content": "19:50 到 20:18 我在地下机房重启冷却泵，工单记录了每一步操作。",
                        "contradicts": "",
                    },
                    {
                        "id": "david_relationship",
                        "topic": "relationship",
                        "truthfulness": "TRUTH",
                        "content": "我和林教授只在设备检修时接触，他常抱怨维护响应太慢。",
                        "contradicts": "",
                    },
                    {
                        "id": "david_last_seen",
                        "topic": "last_seen",
                        "truthfulness": "LIE",
                        "content": "20:22 之前我没看见任何人靠近 B3，也没发现监控异常。",
                        "contradicts": "他早已知道维护通道摄像头存在断续故障。",
                    },
                    {
                        "id": "david_motive",
                        "topic": "motive",
                        "truthfulness": "EVASIVE",
                        "content": "一次报修争执不至于让人杀人，我没有别的可说。",
                        "contradicts": "",
                    },
                    {
                        "id": "david_method",
                        "topic": "method",
                        "truthfulness": "TRUTH",
                        "content": "B3 除了正门还有维护通道，门从内部合上后会自动锁定。",
                        "contradicts": "",
                    },
                    {
                        "id": "david_evidence",
                        "topic": "evidence",
                        "truthfulness": "TRUTH",
                        "content": f"监控虽然断了几秒，但恢复前最后一帧拍到 {bob_name} 从维护通道出来。",
                        "contradicts": "",
                    },
                    {
                        "id": "david_secret",
                        "topic": "secret",
                        "truthfulness": "LIE",
                        "content": "所有监控故障我都按时上报，没有延误过。",
                        "contradicts": "他把维护通道摄像头故障压了两天。",
                    },
                    {
                        "id": "david_general",
                        "topic": "general",
                        "truthfulness": "UNKNOWN",
                        "content": "问设备、门禁或时间，我可以给你准确答案。",
                        "contradicts": "",
                    },
                ],
            },
        ],
        "evidence": [
            {
                "id": "ev_vial",
                "title": "破裂的蓝色试剂瓶",
                "description": "瓶内残留物检出高浓度乌头碱，与死者咖啡中的成分一致。",
                "source": "现场与毒理报告",
                "status": "已验证",
                "dimensions": ["method"],
                "implicates": [],
                "discovery": {"type": "INITIAL"},
            },
            {
                "id": "ev_access",
                "title": "20:01 门禁记录",
                "description": "一张未绑定姓名的临时卡在 20:01 进入 B3，卡号尾号与数据平台主管保管段一致。",
                "source": "门禁后台",
                "status": "已验证",
                "dimensions": ["opportunity", "contradiction"],
                "implicates": ["bob"],
                "discovery": {"type": "ASK", "npc_id": "alice", "topic": "evidence"},
            },
            {
                "id": "ev_camera",
                "title": "维护通道残帧",
                "description": f"20:05 的监控恢复帧拍到 {bob_name} 从 B3 维护通道离开。",
                "source": "维护监控",
                "status": "已验证",
                "dimensions": ["opportunity", "contradiction"],
                "implicates": ["bob"],
                "discovery": {"type": "ASK", "npc_id": "david", "topic": "evidence"},
            },
            {
                "id": "ev_requisition",
                "title": "乌头碱领用单",
                "description": f"18:40，{bob_name} 的账号以“昆虫实验”为由领用乌头碱，但当日没有对应实验。",
                "source": "试剂管理系统",
                "status": "已验证",
                "dimensions": ["method", "motive"],
                "implicates": ["bob"],
                "discovery": {"type": "ASK", "npc_id": "charlie", "topic": "evidence"},
            },
            {
                "id": "ev_watch",
                "title": "智能手表近场记录",
                "description": f"19:43，死者手表记录到与 {bob_name} 工牌的近场接触，推翻其“17 点后未见面”的说法。",
                "source": "死者智能手表",
                "status": "已验证",
                "dimensions": ["motive", "contradiction"],
                "implicates": ["bob"],
                "discovery": {"type": "ASK", "npc_id": "bob", "topic": "last_seen"},
            },
            {
                "id": "ev_glove",
                "title": "咖啡杯上的手套纤维",
                "description": "杯盖检出的灰色丁腈纤维来自数据平台主管专用的防静电手套。",
                "source": "痕迹检验",
                "status": "已验证",
                "dimensions": ["method"],
                "implicates": ["bob"],
                "discovery": {"type": "ASK", "npc_id": "alice", "topic": "method"},
            },
        ],
        "initial_evidence_ids": ["ev_vial"],
        "proof_rule": {
            "minimum_selected": 3,
            "required_dimensions": ["opportunity", "method"],
            "any_of": [
                ["ev_access", "ev_requisition", "ev_vial"],
                ["ev_camera", "ev_glove", "ev_watch"],
                ["ev_camera", "ev_requisition", "ev_vial"],
            ],
        },
    }

